import TopicListScreen, { TopicItem } from '@components/TopicListScreen'

const topics: TopicItem[] = [
  { title: '～んです', screen: 'GrammarNdesuScreen' },
  { title: '～ほうがいいです：Nên/không nên', screen: 'GrammarHougaiiScreen' },
  { title: '～のに: Mặc dù', screen: 'GrammarNoniScreen' },
  { title: '～ながら', screen: 'GrammarNagaraScreen' },
  { title: '～のが、～のは、～のに', screen: 'GrammarNoGaNoHaNoNiScreen' },
  { title: 'Động từ thể khả năng (可能形)', screen: 'GrammarKanoukeiScreen' },
  { title: '～ことができる', screen: 'GrammarKotoGaDekiruScreen' },
  { title: '～かた: Cách (làm gì)', screen: 'GrammarKataScreen' },
  { title: '～とおりに', screen: 'GrammarTooriniScreen' },
  { title: 'Động từ thể ý chí (意思形)', screen: 'GrammarIshikeiScreen' },
  { title: '～ようと思います/～ようと思っています', screen: 'GrammarYouToOmoimasuScreen' },
  { title: '～ようになる/ ～なくなる', screen: 'GrammarYouninaruScreen' },
  { title: '～ようにする', screen: 'GrammarYouniSuruScreen' },
  { title: '～つもりです', screen: 'GrammarTsumoriScreen' },
  { title: '～予定です', screen: 'GrammarYoteiScreen' },
  { title: 'Các mẫu câu sử dụng trợ từ と', screen: 'GrammarToUsageScreen' },
  { title: 'Tự động từ và tha động từ', screen: 'GrammarJidouTadoushiScreen' },
  { title: 'Câu điều kiện ～ば', screen: 'GrammarBaScreen' },
  { title: 'Câu điều kiện ～たら', screen: 'GrammarTaraScreen' },
  { title: 'Câu điều kiện ～と', screen: 'GrammarToScreen' },
  { title: 'Câu điều kiện ～なら', screen: 'GrammarNaraScreen' },
  { title: '～場合は', screen: 'GrammarBaaiScreen' },
  { title: '～とき', screen: 'GrammarTokiScreen' },
  { title: '～よう、～みたい', screen: 'GrammarYouMitaiScreen' },
  { title: '～そうです', screen: 'GrammarSouDesuScreen' },
  { title: '～らしいです', screen: 'GrammarRashiiScreen' },
  {
    title: 'Phân biệt ～よう/ みたい、～そうです và らしいです',
    screen: 'GrammarComparisonScreen',
  },
  { title: '～には', screen: 'GrammarNiWaScreen' },
  { title: '～にする (quyết định/chọn)', screen: 'GrammarNiSuruScreen' },
  { title: 'Tính từ + する: Làm cho …', screen: 'GrammarAdjectiveSuruScreen' },
  { title: 'Phân biệt 「もう」 và「 まだ」', screen: 'GrammarMouMadaScreen' },
  { title: '～ために、～ように', screen: 'GrammarTameniYouniScreen' },
  { title: 'Động từ ghép (複合動詞)', screen: 'GrammarFukugouDoushiScreen' },
  { title: '～すぎる', screen: 'GrammarSugiruScreen' },
  { title: '～やすい、～にくい', screen: 'GrammarYasuiNIkuiScreen' },
  { title: 'Thể bị động (受身形)', screen: 'GrammarUkemiScreen' },
  { title: 'Thể sai khiến (使役形)', screen: 'GrammarShiekikeiScreen' },
  { title: 'Thể mệnh lệnh (命令形)', screen: 'GrammarMeireikeiScreen' },
  {
    title: '～てあげます、～てくれます、～てもらいます',
    screen: 'GrammarTeAgeruKureruMorauScreen',
  },
  { title: '～てしまう', screen: 'GrammarTeShimauScreen' },
  { title: '～てある', screen: 'GrammarTeAruScreen' },
  { title: '～ておく', screen: 'GrammarTeOkuScreen' },
  { title: '～かもしれません、～はずです', screen: 'GrammarKamoshiremasenHasuScreen' },
  { title: '～てみる', screen: 'GrammarTeMiruScreen' },
  { title: '～たらいいですか/ ～たらどうですか', screen: 'GrammarTaraIiDesuKaScreen' },
  { title: '～ていただけませんか', screen: 'GrammarTeItadakemasenScreen' },
  { title: '～か、～かどうか', screen: 'GrammarKaKaDoukaScreen' },
  { title: 'Kính ngữ', screen: 'GrammarKeigoScreen' },
  { title: '〜し〜', screen: 'GrammarShiScreen' },
]
const GrammarN4CategoryScreen = () => {
  return <TopicListScreen screenTitle="Ngữ pháp N4" topics={topics} />
}
export default GrammarN4CategoryScreen
