export type RootStackParamList = {
  Login: undefined
  Register: undefined
  Verify: { email: string }
  Home: undefined
  ForgotPassword: undefined
  VerifyForgotPassword: { email: string }
  ResetPassword: { email: string }
  SelectVocabularyLevel: undefined
  KanaTypeSelection: undefined
  KanaScreen: { type: 'hiragana' | 'katakana' }
  SelectGrammarLevel: undefined
  GrammarN5CategoryScreen: undefined
  GrammarVerbN5TopicListScreen: undefined
  GrammarVerbN5Screen: undefined
  GrammarVerbN5TopicListScreen: undefined
  GrammarVerbN5Screen: undefined
  GrammarVerbMasuScreen: undefined
  GrammarVerbTaFormScreen: undefined
  GrammarTeFormScreen: undefined
  GrammarMasenkaMashouScreen: undefined
  GrammarTaKotoGaAruScreen: undefined
  GrammarAgeruMorauKureruScreen: undefined
  GrammarGaArimasuScreen: undefined
  GrammarTariTariSuruScreen: undefined
  GrammarNaideKudasaiScreen: undefined
  GrammarNakerebaNaranaiScreen: undefined
  GrammarNakerebaIkenaiScreen: undefined
  GrammarNakutemoIiScreen: undefined
  GrammarAdjectiveN5TopicListScreen: undefined
  GrammarAdjectiveBasicScreen: undefined
  GrammarAdjectiveWithNounVerbScreen: undefined
  GrammarAdjectiveNaruScreen: undefined
  GrammarTaiDesuScreen: undefined
  GrammarGaHoshiiDesuScreen: undefined
  GrammarGaSukiDesuScreen: undefined
  GrammarGaJouzuHetaDesuScreen: undefined
  GrammarNounN5TopicListScreen: undefined
  GrammarNounBasicScreen: undefined
  GrammarCountingPeopleThingScreen: undefined
  GrammarDateDayMonthScreen: undefined
  GrammarVerbModifyNounScreen: undefined
  GrammarParticleN5TopicListScreen: undefined
  GrammarParticlesOverviewScreen: undefined
  GrammarParticleNiDeScreen: undefined
  GrammarGaKedoScreen: undefined
  OtherSentencePatternsScreen: undefined
  GrammarKoSoADoScreen: undefined
  GrammarYoriNoHougaScreen: undefined
  GrammarIchibanComparisonScreen: undefined
  GrammarMaeAtoScreen: undefined
  GrammarDakeShikaScreen: undefined
  GrammarNodeKaraScreen: undefined
  GrammarDeshouScreen: undefined
  GrammarAdverbsNegativeScreen: undefined
  GrammarQuestionWordsScreen: undefined
  GrammarN4CategoryScreen: undefined
  GrammarNdesuScreen: undefined
  GrammarHougaiiScreen: undefined
  GrammarNoniScreen: undefined
  GrammarNagaraScreen: undefined
  GrammarNoGaNoHaNoNiScreen: undefined
  GrammarKanoukeiScreen: undefined
  GrammarKotoGaDekiruScreen: undefined
  GrammarKataScreen: undefined
  GrammarTooriniScreen: undefined
  GrammarIshikeiScreen: undefined
  GrammarYouToOmoimasuScreen: undefined
  GrammarYouninaruScreen: undefined
  GrammarYouniSuruScreen: undefined
  GrammarTsumoriScreen: undefined
  GrammarYoteiScreen: undefined
  GrammarToUsageScreen: undefined
  GrammarJidouTadoushiScreen: undefined
  GrammarBaScreen: undefined
  GrammarTaraScreen: undefined
  GrammarToScreen: undefined
  GrammarNaraScreen: undefined
  GrammarBaaiScreen: undefined
  GrammarTokiScreen: undefined
  GrammarYouMitaiScreen: undefined
  GrammarSouDesuScreen: undefined
  GrammarRashiiScreen: undefined
  GrammarComparisonScreen: undefined
  GrammarNiWaScreen: undefined
  GrammarNiSuruScreen: undefined
  GrammarAdjectiveSuruScreen: undefined
  GrammarMouMadaScreen: undefined
  GrammarTameniYouniScreen: undefined
  GrammarFukugouDoushiScreen: undefined
  GrammarSugiruScreen: undefined
  GrammarYasuiNIkuiScreen: undefined
  GrammarUkemiScreen: undefined
  GrammarShiekikeiScreen: undefined
  GrammarMeireikeiScreen: undefined
  GrammarTeAgeruKureruMorauScreen: undefined
  GrammarTeShimauScreen: undefined
  GrammarTeAruScreen: undefined
  GrammarTeOkuScreen: undefined
  GrammarKamoshiremasenHasuScreen: undefined
  GrammarTeMiruScreen: undefined
  GrammarTaraIiDesuKaScreen: undefined
  GrammarTeItadakemasenScreen: undefined
  GrammarKaKaDoukaScreen: undefined
  GrammarKeigoScreen: undefined
  GrammarShiScreen: undefined
  GrammarNaitoNakuchaScreen: undefined
  GrammarChauScreen: undefined
  GrammarTokuScreen: undefined
  GrammarMitaiRashiiPpoiScreen: undefined
  GrammarMarudeYouMitaiScreen: undefined
  GrammarYouniYounaScreen: undefined
  GrammarYouToSuruScreen: undefined
  GrammarBaTaraToIiScreen: undefined
  GrammarBakariScreen: undefined
  GrammarSaeScreen: undefined
  GrammarSaeBaScreen: undefined
  GrammarKosoScreen: undefined
  GrammarTokoroDesuScreen: undefined
  GrammarBekidaScreen: undefined
  GrammarTeShouganaiScreen: undefined
  GrammarTamaranaideScreen: undefined
  GrammarTsumoriDattanoniScreen: undefined
  GrammarTameNiScreen: undefined
  GrammarGaruScreen: undefined
  GrammarTeHoshiiScreen: undefined
  GrammarUchiNiScreen: undefined
  GrammarAidaAidaNiScreen: undefined
  GrammarTabiNiScreen: undefined
  GrammarSaichuuNiScreen: undefined
  GrammarKaraNiKaketeScreen: undefined
  GrammarToIuKotoScreen: undefined
  GrammarKanaScreen: undefined
  GrammarWakeDaScreen: undefined
  GrammarWakeJanaiScreen: undefined
  GrammarWakeNiWaIkanaiScreen: undefined
  GrammarMonoMonScreen: undefined
  GrammarOkageDeScreen: undefined
  GrammarNiChigaiNaiScreen: undefined
  GrammarTteUsageScreen: undefined
  GrammarNankaNanteScreen: undefined
  GrammarKawariniScreen: undefined
  GrammarUeNiScreen: undefined
  GrammarNiKuwaeteScreen: undefined
  GrammarKotoGaAruScreen: undefined
  GrammarOsoreGaAruScreen: undefined
  GrammarNiKimatteIruScreen: undefined
  GrammarNiYotteScreen: undefined
  GrammarToIuPatternsScreen: undefined
  GrammarMonokaScreen: undefined
  GrammarDonnaniKotoKaScreen: undefined
  GrammarToshiteScreen: undefined
  GrammarBaToOmouScreen: undefined
  GrammarN3CategoryScreen: undefined
  GrammarN2CategoryScreen: undefined
  GrammarConditionScreen: undefined
  GrammarReasonScreen: undefined
  GrammarPurposeScreen: undefined
  GrammarContrastScreen: undefined
  GrammarEmphasisScreen: undefined
  GrammarGuessScreen: undefined
  GrammarChangeScreen: undefined
  GrammarLimitScreen: undefined
  GrammarAdviceScreen: undefined
  GrammarStateScreen: undefined
  GrammarTimeScreen: undefined
  GrammarPassiveScreen: undefined
  GrammarNegativeScreen: undefined
  GrammarSpecialScreen: undefined
  GrammarConditionScreen: undefined
  GrammarBakarikaScreen: undefined
  GrammarBaHodoScreen: undefined
  GrammarMonoNaraScreen: undefined
  GrammarToshitaraScreen: undefined
  GrammarNaiKotoNiwaScreen: undefined
  GrammarTatokorodeScreen: undefined
  GrammarMononoScreen: undefined
  GrammarNagaraMoScreen: undefined
  GrammarNishitewaScreen: undefined
  GrammarToIttemoScreen: undefined
  GrammarReasonScreen: undefined
  GrammarOkagedeScreen: undefined
  GrammarSeideScreen: undefined
  GrammarAmariScreen: undefined
  GrammarMonoDakaraScreen: undefined
  GrammarKotoDashiScreen: undefined
  GrammarDakeNiScreen: undefined
  GrammarBakariniScreen: undefined
  GrammarKaraNiwaijouScreen: undefined
  GrammarUewaScreen: undefined
  GrammarBekidaN2Screen: undefined
  GrammarKotoDaScreen: undefined
  GrammarMonoDaScreen: undefined
  GrammarNaiMonokaScreen: undefined
  GrammarKotoWaNaiScreen: undefined
  GrammarTamonodaScreen: undefined
  GrammarNiTsureteScreen: undefined
  GrammarNiShitagatteScreen: undefined
  GrammarToTomoniScreen: undefined
  GrammarNiTomonatteScreen: undefined
  GrammarShidaiDaScreen: undefined
  GrammarIppouScreen: undefined
  GrammarHanmenScreen: undefined
  GrammarKawariniN2Screen: undefined
  GrammarKuseniScreen: undefined
  GrammarToIuYoriScreen: undefined
  GrammarWariniScreen: undefined
  GrammarNishitemoScreen: undefined
  GrammarBakarikaN2Screen: undefined
  GrammarNominarazuScreen: undefined
  GrammarWaMochironScreen: undefined
  GrammarNiKagirazuScreen: undefined
  GrammarNiKakawarazuScreen: undefined
  GrammarNishitewaN2Screen: undefined
  GrammarNiChigainaiScreen: undefined
  GrammarNiSouinaiScreen: undefined
  GrammarNikimatteiruScreen: undefined
  GrammarRashiiN2Screen: undefined
  GrammarPpoiScreen: undefined
  GrammarYounaKigasureScreen: undefined
  GrammarKanoyoudaScreen: undefined
  GrammarWakeganaiScreen: undefined
  GrammarHazuganaiScreen: undefined
  GrammarTowaKagiranaiScreen: undefined
  GrammarNiKagiriScreen: undefined
  GrammarNiKagirazuN2Screen: undefined
  GrammarDakeScreen: undefined
  GrammarNiHokaNaranaiScreen: undefined
  GrammarNiSuginaiScreen: undefined
  GrammarToIuMonodaScreen: undefined
  GrammarNishitemoNishitemoScreen: undefined
  GrammarNishiroNishiroScreen: undefined
  GrammarNiseyoNiseyoScreen: undefined
  GrammarDonnaniKotoKaN2Screen: undefined
  GrammarIkuraTemoScreen: undefined
  GrammarToshitemoScreen: undefined
  GrammarSaserareruScreen: undefined
  GrammarRareruScreen: undefined
  GrammarTeShouganaiN2Screen: undefined
  GrammarTeTamaranaScreen: undefined
  GrammarTeNaranaiScreen: undefined
  GrammarNaiDeWaIrarenaiScreen: undefined
  GrammarZuNiwaIrarenaiScreen: undefined
  GrammarTameniScreen: undefined
  GrammarYouniScreen: undefined
  GrammarNiOujiteScreen: undefined
  GrammarNiSotteScreen: undefined
  GrammarNiwatatteScreen: undefined
  GrammarWoTsuujiteScreen: undefined
  GrammarSueniScreen: undefined
  GrammarAgekuScreen: undefined
  GrammarToIutoScreen: undefined
  GrammarToIeBaScreen: undefined
  GrammarToIuttaraScreen: undefined
  GrammarNiOiteScreen: undefined
  GrammarWoTowazuScreen: undefined
  GrammarWoMegutteScreen: undefined
  GrammarNiSaishiteScreen: undefined
  GrammarNiAtatteScreen: undefined
  GrammarKaneruScreen: undefined
  GrammarKanenaiScreen: undefined
  GrammarTeIraiScreen: undefined
  GrammarShidaiDeScreen: undefined
  GrammarTebakariIruScreen: undefined
  GrammarPpanashiScreen: undefined
  GrammarGachiScreen: undefined
  GrammarKimiScreen: undefined
  GrammarKakeScreen: undefined
  GrammarSaichuuNiN2Screen: undefined
  GrammarUchiNiN2Screen: undefined
  GrammarTokoroNiScreen: undefined
  GrammarTatoTanscreen: undefined
  GrammarKaToOmoutoScreen: undefined
  GrammarKaNaiKaScreen: undefined
  SelectKanjiLevel: undefined
  KanjiN5Screen: undefined
  KanjiN4Screen: undefined
  KanjiN3Screen: undefined
  KanjiN2Screen: undefined
  VocabularyN5LessonListScreen: undefined
  VocabularyN4LessonListScreen: undefined
  VocabularyLessonDetailScreen: {
    lessonNumber: number
    level: 'N5' | 'N4' | 'N3' | 'N2' | 'N1'
  }
  VocabularyN3LessonListScreen: undefined
  VocabularyN2LessonListScreen: undefined
  SelectVocabularyTest: undefined
  ChooseWordCountVocabularyScreen: { level: string }
  VocabularyPracticeScreen: { level: string; count: number; words: VocabularyItem[] }
  SettingsScreen: undefined
  VocabularyResultScreen: {
    level: string
    words: VocabularyItem[]
    answers: {
      selected: string | null
      correct: string
      options: string[]
    }[]
  }
  PracticeScreen: undefined
  SelectGrammarTest: undefined
  SelectKanaTest: undefined
  KanaTestScreen: {
    questions: {
      kana: string
      correct: string
      options: string[]
    }[]
    type: 'hiragana' | 'katakana'
  }

  KanaResultScreen: {
    questions: {
      kana: string
      correct: string
      options: string[]
    }[]
    answers: {
      selected: string | null
      correct: string
    }[]
    type: 'hiragana' | 'katakana'
  }
  SelectKanjiTest: undefined
  KanjiPracticeScreen: {
    level: string
    count: number
    words: KanjiItem[]
  }
  KanjiResultScreen: {
    level: string
    words: KanjiItem[]
    answers: {
      selected: string | null
      correct: string
      options: string[]
    }[]
  }
  ChooseWordCountKanjiScreen: { level: string }
  ChooseGrammarCountScreen: { level: string }
}
